ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "aiScore" DOUBLE PRECISION;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "aiDecision" TEXT;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "aiReason" TEXT;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "aiRiskLevel" TEXT;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "aiReleasePayment" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "aiBlockPayment" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "aiSendToAdmin" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "adminReviewRequired" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "aiEvidence" TEXT;
ALTER TABLE "Dispute" ADD COLUMN IF NOT EXISTS "automationApplied" TEXT;

CREATE INDEX IF NOT EXISTS "Dispute_aiRiskLevel_idx" ON "Dispute"("aiRiskLevel");
CREATE INDEX IF NOT EXISTS "Dispute_adminReviewRequired_idx" ON "Dispute"("adminReviewRequired");
